Repository pyhf/pyhf-benchmark, pull requests merged in 2020-07, with the labels that each got.

#11 feat: Add plot function
  scripts/plot.py
  scripts/run.py
Labels: enhancement

#15 feat: Discard wandb
  scripts/jsonlfile.py
  scripts/plot.py
  scripts/run.py
  scripts/stats.py
  scripts/util.py
Labels: enhancement

#19 feat: Package Project
  .bumpversion.cfg
  .coveragerc
  .github/workflows/ci.yml
  CODE_OF_CONDUCT.md
  MANIFEST.in
  README.md
  binder/postBuild
  pyproject.toml
  pytest.ini
  requirements.txt
  setup.cfg
  setup.py
  src/pyhf_benchmark/__init__.py
  src/pyhf_benchmark/cli/__init__.py
  src/pyhf_benchmark/cli/cli.py
  src/pyhf_benchmark/jsonlfile.py
  src/pyhf_benchmark/plot.py
  src/pyhf_benchmark/run.py
  src/pyhf_benchmark/stats.py
  src/pyhf_benchmark/util.py
  src/pyhf_benchmark/version.py
  tests/test_cli.py
  tests/test_import.py
Labels: documentation, enhancement

#27 docs: Update usage section to use CLI API
  README.md
Labels: documentation
