Repository pyhf/pyhf-benchmark, pull requests merged in 2020-08, with the labels that each got.

#29 fix: Combine plots
  src/pyhf_benchmark/plot.py
  src/pyhf_benchmark/run.py
  src/pyhf_benchmark/stats.py
Labels: fix

#32 build: Remove redundancy in setup extras
  setup.py
Labels: build

#30 test: Add unit tests
  setup.py
  src/pyhf_benchmark/jsonlfile.py
  src/pyhf_benchmark/load.py
  src/pyhf_benchmark/mle.py
  src/pyhf_benchmark/plot.py
  src/pyhf_benchmark/run.py
  tests/test_cli.py
  tests/test_jsonfile.py
  tests/test_load.py
  tests/test_mle.py
  tests/test_patchset/BkgOnly.json
  tests/test_plot.py
  tests/test_stats.py
Labels: refactor, tests
